services:
  biblioteca_blue:
    image: mongo:7.0
    container_name: biblioteca_blue
    hostname: biblioteca_blue
    command: ["--replSet", "rs0", "--bind_ip_all",  "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - biblioteca_blue_data:/data/db
    networks:
      - mongo-net
  replica_biblioteca_blue:
    image: mongo:7.0
    container_name: replica_biblioteca_blue
    hostname: replica_biblioteca_blue
    command: ["--replSet", "rs0", "--bind_ip_all",  "--port", "27019"]
    ports:
      - "27019:27019"
    volumes:
      - replica_biblioteca_blue_data:/data/db
    networks:
      - mongo-net

  replica_biblioteca_blue2:
    image: mongo:7.0
    container_name: replica_biblioteca_blue2
    hostname: replica_biblioteca_blue2
    command: ["--replSet", "rs0", "--bind_ip_all",  "--port", "27020"]
    ports:
      - "27020:27020"
    volumes:
      - replica_biblioteca_blue2_data:/data/db
    networks:
      - mongo-net
networks:
  mongo-net:
    driver: bridge

volumes:
  biblioteca_blue_data:
  replica_biblioteca_blue_data:
  replica_biblioteca_blue2_data:
