# Generated by Django 4.2.11 on 2026-06-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seudononimo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'editorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id_ejemplar', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ejemplar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'genero_literario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio_publicacion', models.CharField(blank=True, max_length=4, null=True)),
                ('titulo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutorLibro',
            fields=[
                ('isbn_libro', models.OneToOneField(db_column='isbn_libro', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ws.libro')),
            ],
            options={
                'db_table': 'autor_libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibroGeneroliterario',
            fields=[
                ('isbn_libro', models.OneToOneField(db_column='isbn_libro', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ws.libro')),
            ],
            options={
                'db_table': 'libro_generoliterario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefonoEditorial',
            fields=[
                ('codigo_editorial', models.OneToOneField(db_column='codigo_editorial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ws.editorial')),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'telefono_editorial',
                'managed': False,
            },
        ),
    ]
